[package]
name = "renderer_from_scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tgaimage = "0.1.1"
minifb = "0.25"
rand = "0.8.5"